version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
    builder: html
    configuration: docs/conf.py

python:
    install:
        - path: .
          method: pip
        - requirements: docs/requirements.txt
